---
- name: Respond to Gitea events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  
  rules:
    - name: Prometheus alert.rules push event
      condition: event.payload.commits is selectattr('modified', 'contains', "README.md")
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default

    - name: Debug all other events
      condition: true
      action:
        debug:
